terraform {
  required_providers {
    unifi = {
      source  = "paultyng/unifi"
      version = "~> 0.41.0"  
    }
  }
  # Backend configuration is automatically generated by terraform-backend-git
  # See git_http_backend.auto.tf (generated automatically)
}

provider "unifi" {
  username = var.username
  password = var.password
  api_url = var.controller_url
  allow_insecure = var.allow_insecure 
  site = var.unifi_site  
}
